### ISSUE TITLE
(enhancement): The capability for accessing the options page should be filterable. 

### ISSUE THREAD

**Issue by mvdhoek1** [laposta/laposta-signup-basic#2]
The capability for accessing the options page is currently 'manage_options'. It would be nice if the capability is filterable so our clients could access the options page with a custom capability.

Location: https://github.com/laposta/laposta-signup-basic/blob/main/src/Plugin.php#L105

**Comment by roelleor** [comment]
Thanks for pointing this out! I will look into it shortly.

**Comment by roelleor** [comment]
You can now filter the capability using the name: 'laposta_signup_basic_settings_page_capability' (also available as a const: \Laposta\SignupBasic\Plugin::FILTER_SETTINGS_PAGE_CAPABILITY).

**Comment by mvdhoek1** [comment]
@roelleor thanks for the addition!
