### ISSUE TITLE
other roles are unable to reset cache / submit

### ISSUE THREAD

**Issue by robertbossaert** [laposta/laposta-signup-basic#3]
This request is related to this issue: https://github.com/laposta/laposta-signup-basic/issues/2

With this fix we can add a capability which allows non-admin users to view the Laposta settings, however they receive a 500 error when trying to "Reset Cache".

I think this is is related to this piece of code:

```php
case 'settings_reset_cache':
                if (user_can(wp_get_current_user(), 'manage_options')) {
                    return $this->c->getSettingsController()->ajaxResetCache();
                }
                break;
```

Could this be altered so that users with permissions can flush the cache?

Edit: they are also not able to submit the form.

**Comment by roelleor** [comment]
Thanks for reporting this issue. This is now fixed with version 1.2.1.
